name: Test

on:
  workflow_dispatch: # enable run button on github.com
  pull_request: # run on all pull requests
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run weekly on Sunday at 12:00am (UTC)

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
