name: Test

on:
  pull_request:

jobs:
  build-npm:
    name: Run NPM install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Test
        run: |
          node -v
          npm -v
          npm install
          npm run test
